version: "3"

services:
  postgres:
    image: "postgres"
    container_name: "java-app-jwt-postgres"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=jwt"

  application:
    build: ./
    container_name: "java-app"
    ports:
      - "8091:8090"
    environment:
      - "db_url_hosts=postgres"
